### PR TITLE
Changed pins variable type from int8_t to int16_t.

### LINKED ISSUE #60: int8_t is limiting the pins that can be used with the library.
This is not an issue per se.

I recently picked up an STM board and tried to convert one of my Adafruit EPD projects for that. The issue is the pins I am using can not be fit in an `int8_t`. For example, I am using a pin PB13, and according to STMduino that equals `205`,  which turns out to be `-51` in an `int8_t`.

I cannot change the pins, because the board is already manufactured. I guess for now I will have a local copy of the library where all the pins are changed to `int16_t`.

Let me know if there is a better way to handle this. 

Thanks in advance.

### PR DESCRIPTION
**Pull request by mirzafahad**
So that we can accommodate pin numbers greater than 128. Fixes #60.

### CODE REVIEW

**Comment by ladyada** [comment]
hiya! thanks so much for submitting a PR! we can review & merge PRs once they have passed continuous integration (CI). that means that code compiles cleanly for all tested platforms, is clang formatted so we maintain the same text formatting for all new code, and is doxygen documented.
if your code isnt passing, check the CI output (click on the red X next to the PR to scroll through the log and find where the error is

here is a tutorial on doxygen: https://learn.adafruit.com/the-well-automated-arduino-library/doxygen

and clang-format: https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format

and overall how to contribute PRs to libraries: https://learn.adafruit.com/contribute-to-arduino-with-git-and-github

once you get that green checkmark that indicates CI has passed, please comment reply to this post so we know its time for another review (we may not get notified on CI pass and miss that its time to look!)

**Comment by mirzafahad** [comment]
Sorry, it took me a while to get back to this. But I have fixed the clang-format now.

**Comment by ladyada** [comment]
all good! epic changes, did you test this with hardware and if so, which? :)

**Comment by mirzafahad** [comment]
I tested it with "Adafruit Feather nRF52 Bluefruit LE - nRF52832" and a STM32Nucleo-L053R8.

**Pull request merged**
